### ISSUE TITLE
Execution flow

### ISSUE THREAD

**Issue by JossMarley** [OP-TEE/optee_os#1330]
Hi,
it could be very useful (at least for me) to provide a trace of all the optee-os functions invoked during a normal session. Given a very simple example (e.g. hello world) it could be amazing if somebody could give me a trace of what is happening, from an optee-os perspective. It is clear from the documentation all the APIs called in optee_client, but I would like to know which functions are invoked in optee_os, starting from the one responsible to load a brand new TA  and ending to the one that starts the execution of the trusted application in the secure world. If somebody can help me I can create some UML (sequence diagrams) that can be useful in the docs.
Can you help me?
Thank you

**Comment by lws-team** [comment]
There are recent patches about gprof in optee_os

https://github.com/OP-TEE/optee_os/commit/1160da7102f3afca6519c792dcc609c42adbab74

The main thing I needed to realize to get a grip on what goes on is the TAs are treated a lot like userland apps with Linux.  They don't have access to Linux apis directly, they must go through syscalls.

I wrote a doc patch about what I had understood here

https://github.com/OP-TEE/optee_os/commit/848944f877522c4dd9cdaeb5cb357c5838091f91

**Comment by jenswi-linaro** [comment]
Compile OP-TEE qemu_virt with DEBUG=1, set a breakpoint at `tee_entry_std()`. After that you're ready to do the exercise yourself. Key functions are, `tee_ta_open_session()`, `tee_ta_init_user_ta_session()` and `user_ta_enter()`.

**Comment by JossMarley** [comment]
Thank you so much. Who is calling `tee_entry_std()`?

**Comment by jenswi-linaro** [comment]
`tee_entry_std()` is called indirectly by the assembly `thread_resume()` when it returns.

**Comment by igoropaniuk** [comment]
@JossMarley 
Everything starts from this vector table here `core/arch/arm/kernel/thread*.S`
```/*
 * Vector table supplied to ARM Trusted Firmware (ARM-TF) at
 * initialization.
 *
 * Note that ARM-TF depends on the layout of this vector table, any change
 * in layout has to be synced with ARM-TF.
 */
FUNC thread_vector_table , :
	b	vector_std_smc_entry
	b	vector_fast_smc_entry
	b	vector_cpu_on_entry
	b	vector_cpu_off_entry
	b	vector_cpu_resume_entry
	b	vector_cpu_suspend_entry
	b	vector_fiq_entry
	b	vector_system_off_entry
	b	vector_system_reset_entry
END_FUNC thread_vector_table

LOCAL_FUNC vector_std_smc_entry , :
	sub	sp, sp, #THREAD_SMC_ARGS_SIZE
	store_xregs sp, THREAD_SMC_ARGS_X0, 0, 7
	mov	x0, sp
	bl	thread_handle_std_smc
	/*
	 * Normally thread_handle_std_smc() should return via
	 * thread_exit(), thread_rpc(), but if thread_handle_std_smc()
	 * hasn't switched stack (error detected) it will do a normal "C"
	 * return.
	 */
	load_xregs sp, THREAD_SMC_ARGS_X0, 1, 8
	add	sp, sp, #THREAD_SMC_ARGS_SIZE
	ldr	x0, =TEESMC_OPTEED_RETURN_CALL_DONE
	smc	#0
	b	.	/* SMC should not return */
END_FUNC vector_std_smc_entry
```
then, for example, flow for `InvokeCommand` :
`tee_entry_std` (default standard SMC handler) -> `entry_invoke_command` -> `tee_dispatch_invoke_command` -> `tee_ta_invoke_command` -> `enter_invoke_cmd` (branching here, depends on the type of TA: for User TAs `user_ta_enter_invoke_cmd` is called; for Static TAs, `static_ta_enter_invoke_cmd` is called)

User TA branch flow:
`user_ta_enter_invoke_cmd`->`user_ta_enter` (maps userspace memory, other preparations etc ) -> `thread_enter_user_mode` (here we jump to usermode, further follows libutee part)->`__utee_entry` -> `entry_invoke_command` -> `TA_InvokeCommandEntryPoint` (actually an entry point of user TA)

Hope it helped

BR,
Igor

**Comment by JossMarley** [comment]
@jenswi-linaro @igoropaniuk thank you so much, you helped me a lot. Another question: inside tee_entry_std there is a switch statement, the case followed depends on `arg->cmd`. I added a new custom case, how can I manage the value of `arg->cmd` so that the switch will follow my case? Who set that variable?

**Comment by jenswi-linaro** [comment]
`arg->cmd` is initialized in the kernel driver in the functions calling `optee_do_call_with_arg()`, see file `drivers/tee/optee/call.c`.

**Comment by JossMarley** [comment]
ok, thanks. So, how can I force the execution of a particular case in the switch in `tee_std_entry`? The procedure for setting `arg->cmd` it is not very clear to me. I added a custom case in the switch, now I would like to follow that case when a particular TA is going to be executed. How can I force that behaviour?

**Comment by jenswi-linaro** [comment]
I don't understand what you're trying to achieve by adding another case to the switch when you still seem to expect a TA to be executed.

**Comment by etienne-lms** [comment]
@JossMarley, to clarify (i hope i won't add confusion):

`tee_std_entry()` mainly gets the "secure service requests" that are invoked from the non-secure world.
Non secure wolrd (i.e linux kernel), forges a request by filling a structure that defines a so-called 'command' and its arguments. Currently defined main commands from non-secure are:
- open a session toward of Trusted Application identified by the Trusted Application UUID.
- invoke a command of a Trusted Application (based on an opened session) with optional parameters
- attempt to cancel a previously invoked command.
- close an already opened session.

In non-secure world, some piece of code forges the request strcture (command + arguments), i.e OP-TEE linux driver.
In secure world, OP-TEE core gets the request, verifies its content and route it to the target service: `tee_std_entry()` is such a initial entry point.

If you want to "define" a new service, you _could_ define a new command ID and implement it in both secure and nonsecure side. However, you _could must easier_ rely on the already specified interface and use the "Trusted Application invocation API" to implement your service: no need to hack the OP-TEE `tee_std_entry()`: you only need to implement a Trusted Application.

Note: services implemented through the Trusted Application invocation API can be easily invoke from non-secure clients as well as from secure Trusted Applications.

From your description, it seems you want your secure service to execute in the OP-TEE secure/privilege layer (not as a userland secure application). To do so, you can define a so-called "pseudo-Trusted-Application" (old decrepated name was "static TA") inside OP-TEE core, and handle your very specific sequence through command IDs that will be specific to your "pseudo-TA". You can find examples of "pseudo-TAs" in **core/arch/arm/sta/**  (will be soon renamed **core/arch/arm/pta/**, see https://github.com/OP-TEE/optee_os/pull/1346)

**Comment by LoicH** [comment]
Hi, I'm commenting since I have an issue debugging the TA related to `hello_world`. 

I'm following this guide: https://github.com/OP-TEE/build/blob/master/docs/debug.md 
(In gdb, load the symbols in `$HOME/devel/optee/optee_os/out/arm/core/tee.elf` and connect to the remote target.)

I tried to follow your explanations @igoropaniuk, you gave a really nice overview of the function calls used to enter the TA up until the `TA_InvokeCommandEntryPoint()` function, but as I follow the path down to `thread_enter_user_mode()`, it leads me to `__thread_enter_user_mode()`, I have the following backtrack:

```
#0  __thread_enter_user_mode () at core/arch/arm/kernel/thread_a32.S:592
#1  0x0e012854 in thread_enter_user_mode (a0=2, a1=474640, a2=1052544, a3=0, user_sp=1052544, entry_func=1054135, is_32bit=true, exit_status0=0xe073b90, 
    exit_status1=0xe073b94) at core/arch/arm/kernel/thread.c:1110
#2  0x0e00e6de in user_ta_enter (err=0xe07df2c <stack_thread+8108>, session=0xe073e10, func=UTEE_ENTRY_FUNC_INVOKE_COMMAND, cmd=0, 
    param=0xe07def8 <stack_thread+8056>) at core/arch/arm/kernel/user_ta.c:437
#3  0x0e00e7de in user_ta_enter_invoke_cmd (s=0xe073e10, cmd=0, param=0xe07def8 <stack_thread+8056>, eo=0xe07df2c <stack_thread+8108>)
    at core/arch/arm/kernel/user_ta.c:489
#4  0x0e0240ee in tee_ta_invoke_command (err=0xe07df2c <stack_thread+8108>, sess=0xe073e10, clnt_id=0x0, cancel_req_to=4294967295, cmd=0, 
    param=0xe07def8 <stack_thread+8056>) at core/kernel/tee_ta_manager.c:616
#5  0x0e01d126 in entry_invoke_command (smc_args=0xe07df98 <stack_thread+8216>, arg=0x10500000, num_params=4) at core/arch/arm/tee/entry_std.c:303
#6  0x0e002448 in tee_entry_std (smc_args=0xe07df98 <stack_thread+8216>) at core/arch/arm/tee/entry_std.c:401
#7  0x0e011b38 in __thread_std_smc_entry (args=0xe07df98 <stack_thread+8216>) at core/arch/arm/kernel/thread.c:594
#8  0x0e00040c in thread_std_smc_entry () at core/arch/arm/kernel/thread_a32.S:349
#9  0x0e00040c in thread_std_smc_entry () at core/arch/arm/kernel/thread_a32.S:349
#10 0x0e00040c in thread_std_smc_entry () at core/arch/arm/kernel/thread_a32.S:349
#11 0x0e00040c in thread_std_smc_entry () at core/arch/arm/kernel/thread_a32.S:349
#12 0x0e00040c in thread_std_smc_entry () at core/arch/arm/kernel/thread_a32.S:349
...
```

The problem is that `__thread_enter_user_mode () ` is only assembly code, and this function seems to call another function by changing the `pc` register, the last line in this function is:

```
/* Call the user function with its arguments */
	movs    pc, r5
```

When I'm there, gdb doesn't know what is going on and outputs:

```
__thread_enter_user_mode () at core/arch/arm/kernel/thread_a32.S:611
611		push	{r6,r7}
(gdb) n 
__thread_enter_user_mode () at core/arch/arm/kernel/thread_a32.S:617
617		mov     lr, #0
(gdb) n 
619		movs    pc, r5
(gdb) n 
0x001015b6 in ?? ()
(gdb) n 
Cannot find bounds of current function
(gdb) n 
Cannot find bounds of current function
(gdb) n 
Cannot find bounds of current function
(gdb) n 
Cannot find bounds of current function
(gdb) n 

```

How can I follow the track and see where I'm going? How can I reach the `TA_InvokeCommandEntryPoint()` function?
