### ISSUE TITLE
Unknown fatal error when processing [] for make all with hikey_debian

### ISSUE THREAD

**Issue by sthomsen1** [OP-TEE/optee_os#1640]
related to ticket #1397 i tried the new hikey_debian build to fix my problems. 
But while `make all` i ran always into the same error: 

```
Ran 247 tests in 1.068s

OK
make[2]: Verzeichnis „/home/sascha/work/hikey_debian/edk2/BaseTools/Tests“ wird verlassen
make[1]: Verzeichnis „/home/sascha/work/hikey_debian/edk2/BaseTools“ wird verlassen
Build environment: Linux-4.8.0-54-generic-x86_64-with-Ubuntu-16.10-yakkety
Build start time: 09:57:49, Jun.27 2017


build.py...
 : error C0DE: Unknown fatal error when processing []
	
(Please send email to edk2-devel@lists.sourceforge.net for help, attaching following call stack trace!)

(Python 2.7.12+ on linux2) Traceback (most recent call last):
  File "/home/sascha/work/hikey_debian/edk2/BaseTools/BinWrappers/PosixLike/../../Source/Python/build/build.py", line 2030, in Main
    MyBuild = Build(Target, Workspace, Option)
  File "/home/sascha/work/hikey_debian/edk2/BaseTools/BinWrappers/PosixLike/../../Source/Python/build/build.py", line 771, in __init__
    self.InitBuild()
  File "/home/sascha/work/hikey_debian/edk2/BaseTools/BinWrappers/PosixLike/../../Source/Python/build/build.py", line 874, in InitBuild
    ErrorCode, ErrorInfo = self.PlatformFile.Validate(".dsc", False)
  File "/home/sascha/work/hikey_debian/edk2/BaseTools/Source/Python/Common/Misc.py", line 1831, in Validate
    RealFile, RealRoot = RealPath2(self.File, self.Root, self.AlterRoot)
  File "/home/sascha/work/hikey_debian/edk2/BaseTools/Source/Python/Common/Misc.py", line 666, in RealPath2
    NewFile = GlobalData.gAllFiles[os.path.normpath(os.path.join(Dir, File))]
  File "/home/sascha/work/hikey_debian/edk2/BaseTools/Source/Python/Common/Misc.py", line 593, in __getitem__
    for F in os.listdir(ParentDir):
  File "/home/sascha/work/hikey_debian/edk2/BaseTools/Source/Python/Common/LongFilePathOs.py", line 56, in listdir
    uList = os.listdir(u"%s" % LongFilePath(path))
OSError: [Errno 2] No such file or directory: 'OpenPlatformPkg'


- Failed -
Build end time: 09:57:50, Jun.27 2017
Build total time: 00:00:00
```

did i miss something ?

**Comment by vchong** [comment]
The manifest xml has been updated as well so please try again from repo init, not repo sync.

**Comment by sthomsen1** [comment]
cool thanks a lot! That was the solution!
