### ISSUE TITLE
mem_usage target and ccache doesn't play well

### ISSUE THREAD

**Issue by jenswi-linaro** [OP-TEE/optee_os#1955]
```
  GEN     ../out-os-qemu/core/tee.mem_usage
Traceback (most recent call last):
  File "./scripts/mem_usage.py", line 162, in <module>
    main()
  File "./scripts/mem_usage.py", line 94, in main
    universal_newlines=True)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ccache arm-linux-gnueabihf-readelf': 'ccache arm-linux-gnueabihf-readelf'
core/arch/arm/kernel/link.mk:255: recipe for target '../out-os-qemu/core/tee.mem_usage' failed
```

**Comment by jenswi-linaro** [comment]
Problem fixed in https://github.com/OP-TEE/optee_os/pull/1956
