### ISSUE TITLE
Some problems with python3.6?

### ISSUE THREAD

**Issue by Mangoymd** [OP-TEE/optee_os#3968]
I got a error "TEEC_InvokeCommand(XXX) failed 0xffff3024 origin 0x3" in my Trusted Application, running on QEMU ARMv8. 

And I find some message in the secure world:
```
D/LD:  ldelf:169 ELF (7fc5c039-0542-4ee1-80af-b4eab2f1998d) at 0x4003f000
D/TC:? 0 tee_ta_close_session:499 csess 0xe17c050 id 1
D/TC:? 0 tee_ta_close_session:518 Destroy session
D/TC:1 0 abort_handler:524 [abort] abort in User mode (TA will panic)
E/TC:? 0 
E/TC:? 0 User TA data-abort at address 0x40014e50 (translation fault)
E/TC:? 0  esr 0x92000007  ttbr0 0x200000e18d020   ttbr1 0x00000000   cidr 0x0
E/TC:? 0  cpu #1          cpsr 0x60000100
E/TC:? 0  x0  0000000040014e50 x1  0000000040056023
E/TC:? 0  x2  0000000000000000 x3  000000004075c730
E/TC:? 0  x4  0000000000000000 x5  000000004075c730
E/TC:? 0  x6  00000000000041a0 x7  0000000040058908
E/TC:? 0  x8  0000000000000040 x9  0000000000000000
E/TC:? 0  x10 0000000000000000 x11 0000000000000000
E/TC:? 0  x12 0000000000000000 x13 000000004075c780
E/TC:? 0  x14 0000000000000000 x15 0000000000000000
E/TC:? 0  x16 0000000000000000 x17 0000000000000000
E/TC:? 0  x18 0000000000000000 x19 00000000000089d0
E/TC:? 0  x20 0000000000000000 x21 0000000000000001
E/TC:? 0  x22 0000000040056023 x23 0000000040608ad0
E/TC:? 0  x24 0000000040058000 x25 00000000000004c0
E/TC:? 0  x26 00000000405e6190 x27 0000000040058780
E/TC:? 0  x28 0000000000000000 x29 000000004075c560
E/TC:? 0  x30 00000000400430f0 elr 0000000040046874
E/TC:? 0  sp_el0 000000004075c560
E/LD:  Status of TA 7fc5c039-0542-4ee1-80af-b4eab2f1998d
E/LD:   arch: aarch64
E/LD:  region  0: va 0x40004000 pa 0x0e300000 size 0x002000 flags rw-s (ldelf)
E/LD:  region  1: va 0x40006000 pa 0x0e302000 size 0x008000 flags r-xs (ldelf)
E/LD:  region  2: va 0x4000e000 pa 0x0e30a000 size 0x001000 flags rw-s (ldelf)
E/LD:  region  3: va 0x4000f000 pa 0x0e30b000 size 0x003000 flags rw-s (ldelf)
E/LD:  region  4: va 0x40012000 pa 0x0e30e000 size 0x001000 flags r--s
E/LD:  region  5: va 0x4003f000 pa 0x00001000 size 0x019000 flags r-xs [0]
E/LD:  region  6: va 0x40058000 pa 0x0001a000 size 0x604000 flags rw-s [0]
E/LD:  region  7: va 0x4065c000 pa 0x0e92c000 size 0x101000 flags rw-s (stack)
E/LD:   [0] 7fc5c039-0542-4ee1-80af-b4eab2f1998d @ 0x4003f000
E/LD:  Call stack:
E/LD:   0x0000000040046874
E/LD:   0x000000004003fa80
E/LD:   0x0000000040049ae4
E/LD:   0x0000000040045c30
E/LD:   0xfffffffffffffffc
D/TC:? 0 user_ta_enter:167 tee_user_ta_enter: TA panicked with code 0xdeadbeef
D/TC:? 0 destroy_ta_ctx_from_session:313 Remove references to context (0xe17c7f0)
D/TC:? 0 destroy_context:298 Destroy TA ctx (0xe17c7f0)
```

Then I try to use the `scripts/symbolize.py` for debugging, I got another error:
```
D/LD:  ldelf:169 ELF (7fc5c039-0542-4ee1-80af-b4eab2f1998d) at 0x4003f000
D/TC:? 0 tee_ta_close_session:499 csess 0xe17c050 id 1
D/TC:? 0 tee_ta_close_session:518 Destroy session
D/TC:1 0 abort_handler:524 [abort] abort in User mode (TA will panic)
E/TC:? 0 
E/TC:? 0 User TA data-abort at address 0x40014e50 (translation fault)
E/TC:? 0  esr 0x92000007  ttbr0 0x200000e18d020   ttbr1 0x00000000   cidr 0x0
E/TC:? 0  cpu #1          cpsr 0x60000100
E/TC:? 0  x0  0000000040014e50 x1  0000000040056023
E/TC:? 0  x2  0000000000000000 x3  000000004075c730
E/TC:? 0  x4  0000000000000000 x5  000000004075c730
E/TC:? 0  x6  00000000000041a0 x7  0000000040058908
E/TC:? 0  x8  0000000000000040 x9  0000000000000000
E/TC:? 0  x10 0000000000000000 x11 0000000000000000
E/TC:? 0  x12 0000000000000000 x13 000000004075c780
E/TC:? 0  x14 0000000000000000 x15 0000000000000000
E/TC:? 0  x16 0000000000000000 x17 0000000000000000
E/TC:? 0  x18 0000000000000000 x19 00000000000089d0
E/TC:? 0  x20 0000000000000000 x21 0000000000000001
E/TC:? 0  x22 0000000040056023 x23 0000000040608ad0
E/TC:? 0  x24 0000000040058000 x25 00000000000004c0
E/TC:? 0  x26 00000000405e6190 x27 0000000040058780
E/TC:? 0  x28 0000000000000000 x29 000000004075c560
E/TC:? 0  x30 00000000400430f0 elr 0000000040046874
E/TC:? 0  sp_el0 000000004075c560
E/LD:  Status of TA 7fc5c039-0542-4ee1-80af-b4eab2f1998d
E/LD:   arch: aarch64
E/LD:  region  0: va 0x40004000 pa 0x0e300000 size 0x002000 flags rw-s (ldelf)
E/LD:  region  1: va 0x40006000 pa 0x0e302000 size 0x008000 flags r-xs (ldelf)
E/LD:  region  2: va 0x4000e000 pa 0x0e30a000 size 0x001000 flags rw-s (ldelf)
E/LD:  region  3: va 0x4000f000 pa 0x0e30b000 size 0x003000 flags rw-s (ldelf)
E/LD:  region  4: va 0x40012000 pa 0x0e30e000 size 0x001000 flags r--s
Traceback (most recent call last):
  File "./optee_os/scripts/symbolize.py", line 510, in <module>
    main()
  File "./optee_os/scripts/symbolize.py", line 502, in main
    symbolizer.write(line)
  File "./optee_os/scripts/symbolize.py", line 449, in write
    elf_idx) +
  File "./optee_os/scripts/symbolize.py", line 349, in sections_in_region
    self.read_sections(elf)
/LD:   0xfffffffffffffffc
D/TC:? 0 user_ta_enter:167 tee_user_ta_enter: TA panicked with code 0xdeadbeef
D/TC:? 0 destroy_ta_ctx_from_session:313 Remove references to context (0xe17c7f0)
D/TC:? 0 destroy_context:298 Destroy TA ctx (0xe17c7f0)  File "./optee_os/scripts/symbolize.py", line 314, in read_sections
    cmd = self.arch_prefix('objdump', elf)
  File "./optee_os/scripts/symbolize.py", line 141, in arch_prefix
    self.set_arch(elf)
  File "./optee_os/scripts/symbolize.py", line 132, in set_arch
    p = subprocess.Popen(['file', '-L', elf], stdout=subprocess.PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1295, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

How can I fix it?

**Comment by jforissier** [comment]
Hi @Mangoymd ,

I met the same problem recently, it I think I have a fix somewhere. Let me find it and I will open a PR.

**Comment by jforissier** [comment]
Actually, the fix I had in mind is merged already (https://github.com/OP-TEE/optee_os/pull/3941).

Can you please check if you have commit d7c22ace31de ("symbolize.py: ignore error if ELF file is not found") in your working branch?

**Comment by Mangoymd** [comment]
Hi @jforissier ,
I didn't commit d7c22ac before，but I still got that error when I used the new symbolize.py.

I found that I didn't notice that the -d parameter was followed by the path of the TA ELF file directory, so I just changed it like
`./optee_os/scripts/symbolize.py -d ./out-br/build/optee_examples-1.0/my_TA/ta/out`

This time it seems it got the ELF file, but the problem is still the same one I met before:
```
E/LD:  Status of TA 7fc5c039-0542-4ee1-80af-b4eab2f1998d
E/LD:   arch: aarch64
E/LD:  region  0: va 0x40004000 pa 0x0e300000 size 0x002000 flags rw-s (ldelf)
E/LD:  region  1: va 0x40006000 pa 0x0e302000 size 0x008000 flags r-xs (ldelf)
E/LD:  region  2: va 0x4000e000 pa 0x0e30a000 size 0x001000 flags rw-s (ldelf)
E/LD:  region  3: va 0x4000f000 pa 0x0e30b000 size 0x003000 flags rw-s (ldelf)
E/LD:  region  4: va 0x40012000 pa 0x0e30e000 size 0x001000 flags r--s
E/LD:  region  5: va 0x4002b000 pa 0x00001000 size 0x019000 flags r-xs [0] .ta_head .text .eh_frame .rodata .gnu.hash .dynsym .dynstr .hash .rela.dyn
E/LD:  region  6: va 0x40044000 pa 0x0001a000 size 0x604000 flags rw-s [0] .dynamic .got .rela.got .data .bss
E/LD:  region  7: va 0x40648000 pa 0x0e92c000 size 0x101000 flags rw-s (stack)
E/LD:   [0] 7fc5c039-0542-4ee1-80af-b4eab2f1998d @ 0x4002b000 (out-br/build/optee_examples-1.0/my_TA/ta/out/7fc5c039-0542-4ee1-80af-b4eab2f1998d.elf)
Traceback (most recent call last):
  File "./optee_os/scripts/symbolize.py", line 512, in <module>
    main()
  File "./optee_os/scripts/symbolize.py", line 504, in main
    symbolizer.write(line)
  File "./optee_os/scripts/symbolize.py", line 468, in write
    self._out.write(self.process_abort(self._saved_abort_line))
  File "./optee_os/scripts/symbolize.py", line 295, in process_abort
    sym = self.symbol_plus_offset(addr)
  File "./optee_os/scripts/symbolize.py", line 226, in symbol_plus_offset
    cmd = self.arch_prefix('nm', elf)
  File "./optee_os/scripts/symbolize.py", line 141, in arch_prefix
    self.set_arch(elf)
  File "./optee_os/scripts/symbolize.py", line 132, in set_arch
    p = subprocess.Popen(['file', '-L', elf], stdout=subprocess.PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1295, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by jforissier** [comment]
@Mangoymd please try to add the path to `tee.elf`, too. It should not be needed since you are analyzing a TA panic but we might have another bug :-/
So, full command:

```
./optee_os/scripts/symbolize.py -d ./out-br/build/optee_examples-1.0/my_TA/ta/out -d ./optee_os/out/arm/core
```

**Comment by Mangoymd** [comment]
Hi @jforissier ,
It works!
Thank you very much for your help!
