### ISSUE TITLE
ModuleNotFoundError: No module named 'wand'

### ISSUE THREAD

**Issue by jeyakuna** [OP-TEE/optee_os#3986]
I am converting PDF to image by using wand.image lib. While create Executable , Am getting this error
Traceback (most recent call last):
  File "myapp.py", line 11, in <module>
  File "e:\apps\anaconda3\envs\envimgcomparelversion\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "ClsImgCompare.py", line 17, in <module>
ModuleNotFoundError: No module named 'wand'
[25172] Failed to execute script myapp

Please help me.

**Comment by jforissier** [comment]
How is this related to OP-TEE?

**Comment by jeyakuna** [comment]
Sorry , I am new to Python dev. I dont understand OP-TEE
