### ISSUE TITLE
optee_example/aes ciphering operation implementation

### ISSUE THREAD

**Issue by Xinyao90** [OP-TEE/optee_os#4084]
I would like to reproduce the aes ciphering operation in the provided optee_example for research purpose. However, the implementation of it not available so far as I searched.

In[ optee-examples/aes/ta/aes_ta.c](https://github.com/linaro-swg/optee_examples/tree/master/aes/ta), static TEE_Result cipher_buffer(void *session, uint32_t param_types, TEE_Param params[4]) method will call TEE_CipherUpdate(), and it will further call _utee_cipher_update(). But _utee_cipher_update() is a UTEE_SYSCALLS which is in the [header file](https://github.com/OP-TEE/optee_os/blob/master/lib/libutee/include/utee_syscalls.h).  

Could you help me to locate the actual implementation of the syscall _utee_cipher_update()? 

Thanks a lot!

**Comment by jbech-linaro** [comment]
Here you go:

```c
$ rg utee_cipher_update                                                                                                              
lib/libutee/tee_api_operations.c
1020:           res = tee_buffer_update(operation, _utee_cipher_update, srcData,
1024:                   res = _utee_cipher_update(operation->state, srcData,
1111:           res = tee_buffer_update(operation, _utee_cipher_update,

lib/libutee/include/utee_syscalls.h
99:TEE_Result _utee_cipher_update(unsigned long state, const void *src,

lib/libutee/arch/arm/utee_syscalls_asm.S
54:        UTEE_SYSCALL _utee_cipher_update, TEE_SCN_CIPHER_UPDATE, 5

$ rg syscall_cipher_update                                                                                                           
core/tee/tee_svc_cryp.c
2634:TEE_Result syscall_cipher_update(unsigned long state, const void *src,

core/include/tee/tee_svc_cryp.h
49:TEE_Result syscall_cipher_update(unsigned long state, const void *src,

core/arch/arm/tee/arch_svc.c
72:     SYSCALL_ENTRY(syscall_cipher_update),
```
In short, they are named "the same", but with different prefix `{utee,syscall}_name_of_call`.

**Comment by Xinyao90** [comment]
@jbech-linaro Thanks a lot for the info. However, I've looked into all of them, and still cannot locate the actual implementation for AES encryption itself. Otherwise, could you let me know what's the AES encryption algorithm you followed?

**Comment by jbech-linaro** [comment]
Here's a call stack from gdb.

```c
#0  _rijndael_ecb_decrypt (skey=0xe190728, pt=0xe19ff78 <stack_thread+6264> "\016<\205\211\022u\334\065\212\234@\027\005\314v\335\020", ct=0xe190aa4 "\374\356\036?\213\342C\301qg\225\300\345[W\312;\266V\023\300\060\262\212\063\350r\023u\"\303k\002") at core/lib/libtomcrypt/src/ciphers/aes/aes.c:478
#1  rijndael_ecb_decrypt (ct=0xe190aa4 "\374\356\036?\213\342C\301qg\225\300\345[W\312;\266V\023\300\060\262\212\063\350r\023u\"\303k\002", pt=0xe19ff78 <stack_thread+6264> "\016<\205\211\022u\334\065\212\234@\027\005\314v\335\020", skey=0xe190728) at core/lib/libtomcrypt/src/ciphers/aes/aes.c:638
#2  0x0e10aca6 in ecb_decrypt (ct=0xe190aa4 "\374\356\036?\213\342C\301qg\225\300\345[W\312;\266V\023\300\060\262\212\063\350r\023u\"\303k\002", pt=0xe19ff78 <stack_thread+6264> "\016<\205\211\022u\334\065\212\234@\027\005\314v\335\020", len=0x10, ecb=0xe190720) at core/lib/libtomcrypt/src/modes/ecb/ecb_decrypt.c:45
#3  0x0e1057de in ltc_ecb_update (ctx=<optimized out>, last_block=<optimized out>, data=0xe190aa4 "\374\356\036?\213\342C\301qg\225\300\345[W\312;\266V\023\300\060\262\212\063\350r\023u\"\303k\002", len=0x10, dst=0xe19ff78 <stack_thread+6264> "\016<\205\211\022u\334\065\212\234@\027\005\314v\335\020") at core/lib/libtomcrypt/ecb.c:66
#4  0x0e126b5c in crypto_cipher_update (ctx=0xe190710, mode=TEE_MODE_DECRYPT, last_block=0x1, data=0xe190aa4 "\374\356\036?\213\342C\301qg\225\300\345[W\312;\266V\023\300\060\262\212\063\350r\023u\"\303k\002", len=0x10, dst=0xe19ff78 <stack_thread+6264> "\016<\205\211\022u\334\065\212\234@\027\005\314v\335\020") at core/crypto/crypto.c:192
```

Depends on where it's called from, but the syscall you're referring to would give this to the callstack also
```c
tee_do_cipher_update
tee_svc_cipher_update_helper
syscall_cipher_update
```
Hope it helps.
