### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by tushar95mahawar** [OP-TEE/optee_os#5649]
C:\edk2>build
Build environment: Windows-10-10.0.22000
Build start time: 15:17:03, Nov.15 2022

build...
 : error C0DE: Unknown fatal error when processing []

(Please send email to edk2-devel@lists.01.org for help, attaching following call stack trace!)

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\build.py", line 2578, in <module>
  File "build\build.py", line 2542, in Main
  File "c:\Users\Public\Documents\BuildPool\BaseTools\build\Source\Python\Common\EdkLogger.py", line 203, in error
Common.BuildToolError.FatalError: 49374

**Comment by tushar95mahawar** [comment]
did i miss something ?

**Comment by jforissier** [comment]
Are you trying to build OP-TEE? What procedure are you following?

You can't build OP-TEE under native Windows; WSL2 maybe.
