### ISSUE TITLE
optee_os panic when try to start hello_world TA with about >=4MB size 

### ISSUE THREAD

**Issue by sichunqin** [OP-TEE/optee_os#6393]
In hello_world TA sample, I add the following line to increase TA size: 
`const char test_char[5 * 1024 * 1024];`

Please note that the 3MB TA can work well. 
On qemu V8, I get the core panic when start the hello world sample by execute "optee_example_hello_world" in normal world: 

The following information is provided by secure world log: 
```
D/TC:? 0 ldelf_syscall_open_bin:163 Lookup user TA ELF 8aaaf200-2450-11e4-abe2-0002a5d5c51b (REE)
D/TC:0 0 core_mmu_xlat_table_alloc:526 xlat tables used 5 / 5
E/TC:0 0 core_mmu_xlat_table_alloc:519 5 xlat tables exhausted
E/TC:0 0 Panic 'Failed to spread pgdir on small tables' at core/mm/core_mmu.c:1907 <core_mmu_map_pages>
E/TC:0 0 TEE load address @ 0xe100000
E/TC:0 0 Call stack:
E/TC:0 0  0x0e10b358
E/TC:0 0  0x0e125388
E/TC:0 0  0x0e13b7f8
E/TC:0 0  0x0e10e028
E/TC:0 0  0x0e10d7e4
E/TC:0 0  0x0e10e768
E/TC:0 0  0x0e125190
E/TC:0 0  0x0e108810
E/TC:0 0  0x0e1089a0
E/TC:0 0  0x0e1089ec
E/TC:0 0  0x0e12e258
E/TC:0 0  0x0e12e444
E/TC:0 0  0x0e12357c
E/TC:0 0  0x0e106da4
E/TC:0 0  0x0e10677c
E/TC:0 0  0x0e104364

```
Callbacks: 
```
#0  core_mmu_map_pages (vstart=251666432, pages=0xe1dd978, num_pages=1323, memtype=MEM_AREA_NSEC_SHM) at core/mm/core_mmu.c:1907
#1  0x000000000e10e02c in mobj_reg_shm_inc_map (mobj=0xe1dd930) at core/arch/arm/mm/mobj_dyn_shm.c:214
#2  0x000000000e10d7e8 in mobj_inc_map (mobj=0xe1dd930) at core/include/mm/mobj.h:106
#3  0x000000000e10e76c in mobj_mapped_shm_alloc (pages=0xe1e02e0, num_pages=1323, page_offset=0, cookie=18446462598820424320) at core/arch/arm/mm/mobj_dyn_shm.c:449
#4  0x000000000e125194 in msg_param_mobj_from_noncontig (buf_ptr=1102823424, size=5418264, shm_ref=18446462598820424320, map_buffer=true) at core/kernel/msg_param.c:141
#5  0x000000000e108814 in get_rpc_alloc_res (arg=0xf0000e0, bt=0, size=5418264) at core/arch/arm/kernel/thread_optee_smc.c:635
#6  0x000000000e1089a4 in thread_rpc_alloc (size=5418264, align=8, bt=0) at core/arch/arm/kernel/thread_optee_smc.c:674
#7  0x000000000e1089f0 in thread_rpc_alloc_payload (size=5418264) at core/arch/arm/kernel/thread_optee_smc.c:679
#8  0x000000000e12e25c in rpc_load (uuid=0x40004000, ta=0xe1fbb88 <stack_thread+6280>, ta_size=0xe1fbb90 <stack_thread+6288>, mobj=0xe1fbb78 <stack_thread+6264>) at core/kernel/ree_fs_ta.c:208
#9  0x000000000e12e448 in ree_fs_ta_open (uuid=0x40004000, h=0xe1e2ef8) at core/kernel/ree_fs_ta.c:260
#10 0x000000000e123580 in ldelf_syscall_open_bin (uuid=0x4001cfb0, uuid_size=16, handle=0x4001cfa0) at core/kernel/ldelf_syscalls.c:166
```

**Comment by jenswi-linaro** [comment]
We're running out of xlat tables. It's unfortunate that we discovered it this late when loading a TA. We should probably try to allocate these in advance for the entire memory range we use for mapping shared memory. That way we'd get the panic consistently during boot instead.

**Comment by liu896285864** [comment]
HI,
I want to run a larger TA, and I want about 70% of the resources on my development board to come to my TA. Can I change the OP-TEE os to get a larger space for the safe world? If so, where should I change the config file.

**Comment by liu896285864** [comment]
您的邮件我已收到，我会尽快查看。

**Comment by jenswi-linaro** [comment]
> HI, I want to run a larger TA, and I want about 70% of the resources on my development board to come to my TA. Can I change the OP-TEE os to get a larger space for the safe world? If so, where should I change the config file.

I guess that depends on the development board you're using.

**Comment by liu896285864** [comment]
您的邮件我已收到，我会尽快查看。
